language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

install: ./gradlew assemble -PsonatypeUsername=argius -PsonatypePassword=
script: ./gradlew test -PsonatypeUsername=argius -PsonatypePassword=
