package minestra.collection;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.OptionalLong;
import java.util.Random;
import java.util.function.LongBinaryOperator;
import java.util.function.LongConsumer;
import java.util.function.LongFunction;
import java.util.function.LongPredicate;
import java.util.function.LongSupplier;
import java.util.function.LongToDoubleFunction;
import java.util.function.LongToIntFunction;
import java.util.function.LongUnaryOperator;
import java.util.stream.LongStream;

/**
 * An immutable array of primitive <code>long</code>.
 */
public interface LongImmArray {

    /**
     * Returns a new array of the specified values.
     * @param a int array
     * @return new array
     */
    static LongImmArray of(long... a) {
        return new LongImmArrayImpl(a);
    }

    /**
     * Returns a new array of the specified values.
     * @param collection collection
     * @return new array
     */
    static LongImmArray of(Collection<Long> collection) {
        return ImmArray.of(collection).mapToLong(Long::longValue);
    }

    /**
     * Returns a new array of the specified values.
     * @param stream stream
     * @return new array
     */
    static LongImmArray of(LongStream stream) {
        return of(stream.toArray());
    }

    /**
     * Returns a new array of generating with specified size and generator.
     * @param size array size to generate
     * @param generator generator
     * @return the array
     */
    static LongImmArray generate(int size, LongSupplier generator) {
        long[] a = new long[size];
        for (int i = 0; i < size; i++) {
            a[i] = generator.getAsLong();
        }
        return of(a);
    }

    /**
     * Returns the array of values which are generated by {@link Random}.
     * If it is necessary to use secure random, use <code>generate(int, IntSupplier)</code> with secure random API.
     * @param size array size
     * @param min minimum value
     * @param max maximum value
     * @return the array
     */
    static LongImmArray random(int size, long min, long max) {
        // if you need SecureRandom, use generate(int, LongSupplier)
        final long distance = max - min + 1;
        Random r = new Random(System.currentTimeMillis());
        long[] a = new long[size];
        for (int i = 0; i < size; i++) {
            a[i] = min + (int) (r.nextDouble() * distance);
        }
        return of(a);
    }

    /**
     * Returns the concatenated array of all specified arrays.
     * @param first the first array
     * @param rest the rest of arrays
     * @return the concatenated array
     */
    default LongImmArray concat(LongImmArray first, LongImmArray... rest) {
        final int selfLength = size();
        final int firstLength = first.size();
        int newLength = selfLength;
        newLength += firstLength;
        for (LongImmArray o : rest) {
            newLength += o.size();
        }
        // XXX copy twice
        long[] a = Arrays.copyOf(toArray(), newLength);
        int p = selfLength;
        System.arraycopy(first.toArray(), 0, a, p, firstLength);
        p += firstLength;
        for (LongImmArray o : rest) {
            final int length = o.size();
            System.arraycopy(o.toArray(), 0, a, p, length);
            p += length;
        }
        return of(a);
    }

    /**
     * Returns the number of elements in this array.
     * @return the number of elements
     */
    int size();

    /**
     * Returns the element at the specified index in this array.
     * @param index index of an desired element
     * @return the element
     */
    long at(int index);

    /**
     * Returns an empty array.
     * @return the empty array
     */
    static LongImmArray empty() {
        return LongImmArrayImpl.EMPTY;
    }

    /**
     * Performs apply function as an action to each element of this array.
     * @param action action to apply to each element
     */
    default void forEach(LongConsumer action) {
        final int n = size();
        for (int i = 0; i < n; i++) {
            action.accept(at(i));
        }
    }

    /**
     * Returns whether this array is empty.
     * @return <code>true</code> if this is empty.
     */
    default boolean isEmpty() {
        return size() == 0;
    }

    /**
     * Returns whether the element which satisfies predicate exists in this array.
     * @param pred predicate
     * @return <code>true</code> if the element exists
     */
    default boolean exists(LongPredicate pred) {
        final int n = size();
        for (int i = 0; i < n; i++) {
            if (pred.test(at(i))) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns whether this array contains the element which is same as specified element.
     * @param value value to find
     * @return <code>true</code> if this array contains specified element
     */
    default boolean contains(long value) {
        final int n = size();
        for (int i = 0; i < n; i++) {
            if (at(i) == value) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns an optional value which satisfies specified predicate from the beginning in this array.
     * @param pred predicate
     * @return the optional value
     */
    default OptionalLong find(LongPredicate pred) {
        return find(pred, 0);
    }

    /**
     * Returns an optional value which satisfies specified predicate after the specified index in this array.
     * @param pred predicate
     * @param start number of beginning index to find
     * @return the element as an optional value
     */
    default OptionalLong find(LongPredicate pred, int start) {
        final int n = size();
        for (int i = start; i < n; i++) {
            final long value = at(i);
            if (pred.test(value)) {
                return OptionalLong.of(value);
            }
        }
        return OptionalLong.empty();
    }

    /**
     * Returns the index of first element which is same as specified value in this array.
     * @param value value to find
     * @return number of the index, returns <code>-1</code> if not found
     */
    default int indexOf(long value) {
        final int n = size();
        for (int i = 0; i < n; i++) {
            if (at(i) == value) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Returns the index of element which is the first match of the specified predicate in this array.
     * @param pred predicate
     * @return number of the index, returns <code>-1</code> if not found
     */
    default int indexWhere(LongPredicate pred) {
        final int n = size();
        for (int i = 0; i < n; i++) {
            if (pred.test(at(i))) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Returns the first element of this array if it is not empty.
     * @return the first element as an optional value
     */
    default OptionalLong head() {
        return (size() == 0) ? OptionalLong.empty() : OptionalLong.of(at(0));
    }

    /**
     * Returns the tail elements of this array if exists.
     * @return the tail elements as an array
     */
    default LongImmArray tail() {
        return slice(1, Integer.MAX_VALUE);
    }

    /**
     * Returns a new array of elements that taken out the specified number of from the beginning of this array.
     * @param count count to take
     * @return the array
     */
    default LongImmArray take(int count) {
        return (count == 0) ? empty() : slice(0, count - 1);
    }

    /**
     * Returns a new array of elements that taken out while specified predicate matches from the beginning of this array.
     * @param pred predicate
     * @return the array
     */
    default LongImmArray takeWhile(LongPredicate pred) {
        final int index = indexWhere(pred.negate());
        return (index > 0) ? slice(0, index - 1) : empty();
    }

    /**
     * Returns the rest of the array that drops the specified number of elements in this array.
     * @param count count to drop
     * @return the array
     */
    default LongImmArray drop(int count) {
        final int n = size();
        return (count >= n) ? empty() : slice(count, n);
    }

    /**
     * Returns the rest of the array that drops elements which the specified predicate matches in this array.
     * @param pred predicate
     * @return the array
     */
    default LongImmArray dropWhile(LongPredicate pred) {
        final int index = indexWhere(pred.negate());
        return (index >= 0) ? drop(index) : empty();
    }

    /**
     * Returns the slice of this array.
     * @param from inclusive index of first
     * @param to exclusive index of end
     * @return the array
     */
    default LongImmArray slice(int from, int to) {
        final int n = size() - 1;
        final int to0 = (to < n) ? to : n;
        return new LongImmArrayImpl(true, Arrays.copyOfRange(toArray(), from, to0 + 1));
    }

    /**
     * Returns an array created by applying a function to each of the elements of this array.
     * @param mapper function as a mapper
     * @return the array
     */
    default LongImmArray map(LongUnaryOperator mapper) {
        final int n = size();
        long[] a = new long[n];
        for (int i = 0; i < n; i++) {
            a[i] = mapper.applyAsLong(at(i));
        }
        return of(a);
    }

    /**
     * Returns an object array created by applying a function to each of the elements of this array.
     * @param <R> type of result array elements
     * @param mapper function as a mapper
     * @return the mapping array
     */
    default <R> ImmArray<R> mapToObj(LongFunction<R> mapper) {
        final int n = size();
        List<R> a = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            a.add(mapper.apply(at(i)));
        }
        return ImmArray.of(a);
    }

    /**
     * Returns an int array created by applying a function to each of the elements of this array.
     * @param mapper function as a mapper
     * @return the mapping array
     */
    default IntImmArray mapToInt(LongToIntFunction mapper) {
        final int n = size();
        int[] a = new int[n];
        for (int i = 0; i < n; i++) {
            a[i] = mapper.applyAsInt(at(i));
        }
        return IntImmArray.of(a);
    }

    /**
     * Returns a double array created by applying a function to each of the elements of this array.
     * @param mapper function as a mapper
     * @return the mapping array
     */
    default DoubleImmArray mapToDouble(LongToDoubleFunction mapper) {
        final int n = size();
        double[] a = new double[n];
        for (int i = 0; i < n; i++) {
            a[i] = mapper.applyAsDouble(at(i));
        }
        return DoubleImmArray.of(a);
    }

    default ImmArray<Long> boxed() {
        return mapToObj(Long::valueOf);
    }

    /**
     * Returns the result that reduce elements of this array with the specified binary operator.
     * @param op binary operator
     * @return the result as optional, or optional empty if this array is empty
     */
    default OptionalLong reduce(LongBinaryOperator op) {
        final int n = size();
        if (n == 0) {
            return OptionalLong.empty();
        }
        long result = at(0);
        for (int i = 1; i < n; i++) {
            result = op.applyAsLong(result, at(i));
        }
        return OptionalLong.of(result);
    }

    /**
     * Returns the result that reduce elements of this array with the specified binary operator.
     * @param identity identity element
     * @param op binary operator
     * @return the result
     */
    default long reduce(long identity, LongBinaryOperator op) {
        final int n = size();
        if (n == 0) {
            return identity;
        }
        long result = identity;
        for (int i = 0; i < n; i++) {
            result = op.applyAsLong(result, at(i));
        }
        return result;
    }

    /**
     * Returns the result of folding the elements of this array by the specified operator.
     * @param value initial value
     * @param f binary operator
     * @return the result
     */
    default long fold(long value, LongBinaryOperator f) {
        switch (size()) {
            case 0:
                return value;
            case 1:
                return f.applyAsLong(value, at(0));
            default:
                return f.applyAsLong(value, tail().fold(at(0), f));
        }
    }

    /**
     * Returns a new array which consists with unique elements.
     * @return the array
     */
    default LongImmArray distinct() {
        return of(stream().distinct());
    }

    /**
     * Returns the result of filtering the elements of this array by specified predicate.
     * @param pred predicate
     * @return the array
     */
    default LongImmArray filter(LongPredicate pred) {
        final int n = size();
        int p = 0;
        long[] a = new long[n];
        for (int i = 0; i < n; i++) {
            long x = at(i);
            if (pred.test(x)) {
                a[p++] = x;
            }
        }
        return new LongImmArrayImpl(Arrays.copyOf(a, p));
    }

    /**
     * Returns the sum of elements in this array.
     * @return the sum
     */
    long sum();

    /**
     * Returns the product of elements in this array.
     * @return the product
     */
    long product();

    /**
     * Returns the mean value of elements in this array.
     * If this stream is empty, returns empty optional.
     * @return the mean value
     */
    default double average() {
        return sum() * 1d / size();
    }

    /**
     * Returns a maximum value as optional in this array.
     * If this stream is empty, returns empty optional.
     * @return the maximum value
     */
    OptionalLong max();

    /**
     * Returns a minimum value as optional in this array.
     * If this stream is empty, returns empty optional.
     * @return the minimum value
     */
    OptionalLong min();

    /**
     * Returns new array which is sorted this array in natural order.
     * @return the sorted array
     */
    default LongImmArray sort() {
        long[] a = toArray();
        Arrays.sort(a);
        return of(a);
    }

    /**
     * Returns new array which is sorted this array with specified order.
     * @param cmp order
     * @return the sorted array
     */
    default LongImmArray sortWith(LongComparator cmp) {
        return sortWith(0, size() - 1, cmp);
    }

    /**
     * Returns new array which is sorted this array with specified order.
     * @param fromIndex from
     * @param toIndex to
     * @param cmp order
     * @return the sorted array
     */
    LongImmArray sortWith(int fromIndex, int toIndex, LongComparator cmp);

    /**
     * Returns new array which is reversed the order of elements in this array.
     * @return the array
     */
    default LongImmArray reverse() {
        long[] a = toArray();
        final int size = a.length;
        final int n = a.length / 2;
        for (int i = 0, j = size - 1; i < n; i++, j--) {
            long x = a[j];
            a[j] = a[i];
            a[i] = x;
        }
        return of(a);
    }

    /**
     * Returns this array as a native array.
     * @return the array
     */
    long[] toArray();

    /**
     * Returns the stream which consist same elements in this array.
     * @return the stream
     */
    default LongStream stream() {
        return LongStream.of(toArray());
    }

}
